import { useEthereum } from '@decentology/hyperverse-ethereum/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { Connect } = useEthereum()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{' '}
          <a
            target="_blank"
            rel="noreferrer"
            href="https://www.decentology.com/hyperverse"
          >
            Hyperverse
          </a>{' '}
          + <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by creating your tenant in &nbsp;
          <a
            target="_blank"
            rel="noreferrer"
            href="https://www.decentology.com/hyperverse"
          >
            eth.hyperverse.dev
          </a>
          <br />
          and updating the Tenant ID to your account in
          <code className={styles.code}>pages/_app.tsx</code>
        </p>

        <Connect />

        <div className={styles.grid}>
          <a
            target="_blank"
            rel="noreferrer"
            href="https://docs.hyperverse.dev/"
            className={styles.card}
          >
            <h2>Hyperverse Docs &rarr;</h2>
            <p>Build web3 applications without writing smart contract code.</p>
          </a>
          <a
            target="_blank"
            rel="noreferrer"
            href="https://samples.hyperverse.dev/erc721-storybook/"
            className={styles.card}
          >
            <h2>ERC721 Storybook &rarr;</h2>
            <p>
              View ERC721 functions and how to utilize them in your
              dapp
            </p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Next.js Docs &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
